#Find first root login password
#docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
version: '3.6'
services:
 web:
  image: 'gitlab-ce:18.8.2-ce.0'
  container_name: gitlab
  restart: always
  ports:
   - '80:80'
   - '443:443'
   - '22:22'
  volumes:
    - 'gitlab_config:/etc/gitlab'
    - 'gitlab_log:/var/log/gitlab'
    - 'gitlab_data:/var/opt/gitlab'
   shm_size: '2gb'

volumes:
 gitlab_config: {}
 gitlab_log: {}
 gitlab_data: {}
